# Pandas를 활용한 데이터 처리 및 연산

In [1]:
import pandas as pd

### DataFrame 기본 형식 (Syntax Blueprint)

In [2]:
# pandas.DataFrame(data=None, index=None, columns=None, dtype=None)

### Pandas 데이터 타입 (dtype vs type)

In [3]:
# int64    - integer
# float64  - decimal
# object   - string
# bool     - boolean
# datetime64 - date & time
# category - category

### 생성 기법 1: 칼럼명 지정

In [4]:
df = pd.DataFrame(
    data=[[10,40],[20,50],[30,60]],
    columns=['c1','c2']
)
df

   c1  c2
0  10  40
1  20  50
2  30  60

### 생성 기법 2: 인덱스명 지정

In [5]:
df = pd.DataFrame(
    data=[[10,40],[20,50],[30,60]],
    index=[1,2,3]
)
df

    0   1
1  10  40
2  20  50
3  30  60

### 생성 기법 3: 전면 제어 (Full Control)

In [6]:
df = pd.DataFrame(
    data={'c1':[10,20,30], 'c2':[40,50,60]},
    index=[1,2,3]
)
df

   c1  c2
1  10  40
2  20  50
3  30  60

### NumPy 연동 프레임워크 (NumPy Integration)

In [7]:
import numpy as np

### NumPy 1차 배열 변환

In [8]:
# Step 1: NumPy 배열 생성
arr = np.array([[10,20,30],
                [40,50,60]])

# Step 2: DataFrame 주입
df = pd.DataFrame(arr)
df

    0   1   2
0  10  20  30
1  40  50  60

### 배열 및 다중 파라미터 동시 적용

In [9]:
arr = np.array([[10,40],
                [20,50],
                [30,60]])

df = pd.DataFrame(arr, index=[1,2,3], columns=['c1','c2'])
df

   c1  c2
1  10  40
2  20  50
3  30  60

### 대체 호출 문법 (Alternative Import)

In [10]:
# 기본 방식
import pandas as pd
a = pd.DataFrame(data=[[10,40],[20,50],[30,60]])
a

    0   1
0  10  40
1  20  50
2  30  60

In [11]:
# 클래스 직접 호출
from pandas import DataFrame as df
a = df(data=[[10,40],
             [10,50],
             [30,60]])
a

    0   1
0  10  40
1  10  50
2  30  60

### 딕셔너리 연동 프레임워크 (Dictionary Integration)

In [12]:
dic = {'c1':[10,20,30], 'c2':[40,50,60]}
df = pd.DataFrame(dic)
df

   c1  c2
0  10  40
1  20  50
2  30  60

---
## Step 2. 행과 열 추가/삭제하기

### 행(Row) 추가: .loc[] 인덱서

In [13]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
print("Before:")
print(df)

df.loc[3] = ['song', 95, 80]
print("\nAfter:")
print(df)

Before:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

After:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100
3  song   95   80

### 단일 열 추가 아키텍처

In [14]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
print("Before:")
print(df)

df['math'] = [70, 85, 90]
print("\nAfter:")
print(df)

Before:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

After:
   name  kor  eng  math
0  hong   80   80    70
1   kim   90   95    85
2   heo   75  100    90

### 행/열 삭제: drop() 메서드

In [15]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
df

   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

### axis=0 (행 삭제) vs axis=1 (열 삭제)

In [16]:
# axis=0: 행 삭제
df_row_dropped = df.drop(0, axis=0)
print("행 삭제 (index=0):")
print(df_row_dropped)

행 삭제 (index=0):
  name  kor  eng
1  kim   90   95
2  heo   75  100

In [17]:
# axis=1: 열 삭제
df_col_dropped = df.drop('eng', axis=1)
print("열 삭제 (eng):")
print(df_col_dropped)

열 삭제 (eng):
   name  kor
0  hong   80
1   kim   90
2   heo   75

### inplace 파라미터

In [18]:
# inplace=False (기본값): 원본 보존, 새로운 DataFrame 반환
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
new_df = df.drop(0, axis=0)
print("원본 df:")
print(df)
print("\nnew_df:")
print(new_df)

원본 df:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

new_df:
  name  kor  eng
1  kim   90   95
2  heo   75  100

In [19]:
# inplace=True: 원본 DataFrame 자체를 즉시 변형
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
df.drop(0, axis=0, inplace=True)
print("원본 df (inplace=True 적용 후):")
print(df)

원본 df (inplace=True 적용 후):
  name  kor  eng
1  kim   90   95
2  heo   75  100

---
## Step 3. 행, 열, 원소 선택하기

### 행 추출 1: loc 메커니즘

In [20]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})

# 단일 행 선택
print("df.loc[0]:")
print(df.loc[0])

df.loc[0]:
name    hong
kor       80
eng       80
Name: 0, dtype: object

In [21]:
# 범위 지정 선택 (끝행 포함)
print("df.loc[0:1]:")
print(df.loc[0:1])

df.loc[0:1]:
   name  kor  eng
0  hong   80   80
1   kim   90   95

### 행 추출 2: iloc 메커니즘

In [22]:
# 단일 행 선택
print("df.iloc[2]:")
print(df.iloc[2])

df.iloc[2]:
name    heo
kor      75
eng     100
Name: 2, dtype: object

In [23]:
# 범위 지정 및 슬라이싱 (끝인덱스 제외)
print("df.iloc[1:3]:")
print(df.iloc[1:3])

df.iloc[1:3]:
  name  kor  eng
1  kim   90   95
2  heo   75  100

### iloc 슬라이싱 심화 규칙

In [24]:
# 역방향 추출 (Step = -1)
print("df.iloc[::-1]:")
print(df.iloc[::-1])

df.iloc[::-1]:
   name  kor  eng
2   heo   75  100
1   kim   90   95
0  hong   80   80

In [25]:
# 전체 추출
print("df.iloc[:]:")
print(df.iloc[:])

df.iloc[:]:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

### 열(Column) 타겟팅: 단일 vs 다중

In [26]:
# [1차원] 1개의 열 선택 -> Series
print("df['name']:")
print(df['name'])
print(type(df['name']))

df['name']:
0    hong
1     kim
2     heo
Name: name, dtype: object
<class 'pandas.core.series.Series'>

In [27]:
# [2차원] 여러 개의 열 선택 -> DataFrame
print("df[['name','kor']]:")
print(df[['name','kor']])
print(type(df[['name','kor']]))

df[['name','kor']]:
   name  kor
0  hong   80
1   kim   90
2   heo   75
<class 'pandas.core.frame.DataFrame'>

### 원소 정밀 조준 1: loc 교차점

In [28]:
# 단일 추출: hong의 eng 점수
print("df.loc[0, 'eng']:")
print(df.loc[0, 'eng'])

df.loc[0, 'eng']:
80

In [29]:
# 다중 추출: kim의 eng, kor 점수
print("df.loc[1, ['eng', 'kor']]:")
print(df.loc[1, ['eng', 'kor']])

df.loc[1, ['eng', 'kor']]:
eng    95
kor    90
Name: 1, dtype: object

### 원소 정밀 조준 2: iloc 좌표계

In [30]:
# 단일 추출: hong의 eng 점수 (행 0, 열 2)
print("df.iloc[0, 2]:")
print(df.iloc[0, 2])

df.iloc[0, 2]:
80

In [31]:
# 다중 추출: kim의 eng, kor 점수 (행 1, 열 [2, 1])
print("df.iloc[1, [2, 1]]:")
print(df.iloc[1, [2, 1]])

df.iloc[1, [2, 1]]:
eng    95
kor    90
Name: 1, dtype: object

---
## Step 4. 데이터 위치 변경하기

### 행 위치 재조합: reindex()

In [32]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
print("Before:")
print(df)

df = df.reindex(index=[2, 0, 1])
print("\nAfter (reindex=[2,0,1]):")
print(df)

Before:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

After (reindex=[2,0,1]):
   name  kor  eng
2   heo   75  100
0  hong   80   80
1   kim   90   95

### 열 위치 재조합: 대괄호 재나열

In [33]:
df = pd.DataFrame({'name':['hong','kim','heo'],'eng':[80,95,100],'kor':[80,90,75]})
print("Before:")
print(df)

df = df[['name', 'kor', 'eng']]
print("\nAfter (열 순서 변경):")
print(df)

Before:
   name  eng  kor
0  hong   80   80
1   kim   95   90
2   heo  100   75

After (열 순서 변경):
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

### 축 완전 변환: 행/열 전치 (Transpose)

In [34]:
df = pd.DataFrame({'name':['hong','kim','heo'],'kor':[80,90,75],'eng':[80,95,100]})
print("원본:")
print(df)

# 정식 메서드
print("\ndf.transpose():")
print(df.transpose())

# 단축 속성
print("\ndf.T:")
print(df.T)

원본:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

df.transpose():
         0    1    2
name  hong  kim  heo
kor     80   90   75
eng     80   95  100

df.T:
         0    1    2
name  hong  kim  heo
kor     80   90   75
eng     80   95  100