# 3주차: Pandas 활용 데이터 처리 및 연산

## 1-1. 평균값 (Mean)

### 평균값 함수 구조
```
DataFrame.mean(axis=None, skipna=None)
```
- **axis**: 0 → 행 기준 연산(기본값) / 1 → 열 기준 연산
- **skipna**: True → NaN/Null 제외(기본값) / False → NaN 포함 연산

### 평균값 산출 (기본값)
- skipna=True, axis=0 (기본 설정 적용)

In [2]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.mean()

X    2.00
Y    4.75
dtype: float64

### 평균값 산출 (결측치 포함)
- skipna=False 적용 시 연산 결과

In [3]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.mean(skipna=False)

X     NaN
Y    4.75
dtype: float64

### 평균값 산출 (열 기준 연산)
- axis=1 적용 (행을 따라 각 열의 평균 산출)

In [4]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.mean(axis=1)

0    2.5
1    2.5
2    8.0
3    3.5
dtype: float64

---
## 1-2. 중간값 (Median)

### 중간값 함수 구조
```
DataFrame.median(axis=None, skipna=None)
```
- **axis**: 0 → 행 방향(기본값) / 1 → 열 방향
- **skipna**: True → NaN 제외(기본값) / False → NaN 포함

### 중간값 산출
- df.median() 실행 (NaN 자동 제외)

In [5]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.median()

X    2.0
Y    4.0
dtype: float64

---
## 1-3. 최빈값 (Mode)

### 최빈값 산출

In [6]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.mode()

     X    Y
0  1.0  4.0
1  2.0  NaN
2  3.0  NaN

---
## 1-4. 최솟값 (Min)

### 최솟값 산출

In [7]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

print('최솟값:')
print(df.min())

print('\n최솟값 인덱스:')
print(df.idxmin())

최솟값:
X    1.0
Y    3.0
dtype: float64

최솟값 인덱스:
X    0
Y    1
dtype: int64

---
## 1-5. 최댓값 (Max)

### 최댓값 산출

In [8]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

print('최댓값:')
print(df.max())

print('\n최댓값 인덱스:')
print(df.idxmax())

최댓값:
X    3.0
Y    8.0
dtype: float64

최댓값 인덱스:
X    3
Y    2
dtype: int64

---
# Part 2. Pandas DataFrame 통계 함수
## 산포도(Dispersion) 및 상관관계(Correlation) 분석

## 2-1. 표준편차 (Standard Deviation)

### 표준편차 함수 구조
```
DataFrame.std(axis=None, skipna=None)
```
- **axis**: 행(0) 또는 열(1)을 기준으로 표준편차 계산 방향 설정
- **skipna**: 결측치(NA/null) 제외 여부 설정 (기본값: True)

### 표준편차 산출

In [9]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.std()

X    1.000000
Y    2.217356
dtype: float64

---
## 2-2. 분산 (Variance)

### 분산 함수 구조
```
DataFrame.var(axis=None, skipna=None)
```
- **axis**: 기준 축 설정 (기본값: 0)
- **skipna**: 결측치 처리 (기본값: True)

### 분산 산출

In [10]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.var()

X    1.000000
Y    4.916667
dtype: float64

---
## 2-3. 공분산 (Covariance)

### 공분산 산출

In [11]:
import pandas as pd

df = pd.DataFrame({'X': [1, 2, None, 3],
                   'Y': [4, 3, 8, 4]})

df.cov()

              X             Y
X  1.000000e+00  1.110223e-16
Y  1.110223e-16  4.916667e+00

---
# Part 3. 상관계수 (Correlation Coefficient)

### 상관계수 함수 구조
```
DataFrame.corr(method='pearson', min_periods=1)
```
- **method**: 상관계수 산출 방식 지정 → 'pearson'(기본값), 'spearman', 'kendall'
- **min_periods**: 유효한 결과를 얻기 위한 최소 관측치 수 지정

---
## 3-1. 피어슨 (Pearson) 상관계수

### 피어슨 상관계수 실행

In [13]:
import pandas as pd

df = pd.DataFrame({'name': ['hong', 'kim', 'heo'],
                   'kor': [80, 90, 75],
                   'eng': [80, 95, 100]})

print('데이터 확인:')
print(df)

print('\n피어슨 상관계수:')
print(df.drop('name', axis=1).corr(method='pearson'))

데이터 확인:
   name  kor  eng
0  hong   80   80
1   kim   90   95
2   heo   75  100

피어슨 상관계수:
          kor       eng
kor  1.000000 -0.052414
eng -0.052414  1.000000