## Pandas의 인덱스(Index) 처리

## 1. 위치 기반 인덱싱 개념

In [2]:
import pandas as pd

df = pd.DataFrame(
    data=[
        ['홍길동', 80, 90, 85],
        ['이기자', 70, 75, 85],
        ['최신', 100, 90, 95]
    ],
    index=[1, 2, 3],
    columns=['name', 'kor', 'eng', 'mat']
)
df

  name  kor  eng  mat
1  홍길동   80   90   85
2  이기자   70   75   85
3   최신  100   90   95

## 2. 기본 슬라이싱 코드

In [3]:
df[0:1]

  name  kor  eng  mat
1  홍길동   80   90   85

## 3. .iloc 단일 행 추출

In [4]:
df.iloc[0]

name    홍길동
kor      80
eng      90
mat      85
Name: 1, dtype: object

## 4. .iloc 복합 추출 (행 + 열)

In [5]:
df.iloc[0:2, [0, 2]]

  name  eng
1  홍길동   90
2  이기자   75

## 5. 불리언 인덱싱 (Boolean Indexing)

### 5-1. 불리언 조건식 생성

In [6]:
df.eng >= 90

1     True
2    False
3     True
Name: eng, dtype: bool

### 5-2. 불리언 인덱싱 적용

In [7]:
df[df.eng >= 90]

  name  kor  eng  mat
1  홍길동   80   90   85
3   최신  100   90   95

### 5-3. .loc와 불리언의 결합

In [8]:
df.loc[df.eng >= 90, ['name', 'eng']]

  name  eng
1  홍길동   90
3   최신   90

## 6. Pandas 인덱싱 마스터 요약
- 기본 슬라이싱: df[]
- 위치 기반: df.iloc[]
- 라벨 기반: df.loc[]

## 7. 특정 열을 인덱스로 (set_index)

### 7-1. set_index 실행을 위한 데이터 준비

In [9]:
import pandas as pd

df = pd.DataFrame(
    data=[
        ['홍길동', 80, 90, 85],
        ['이기자', 70, 75, 85],
        ['최신', 100, 90, 95]
    ],
    index=[1, 2, 3],
    columns=['name', 'kor', 'eng', 'mat']
)
df

  name  kor  eng  mat
1  홍길동   80   90   85
2  이기자   70   75   85
3   최신  100   90   95

### 7-2. 'name' 칼럼 인덱스 승격

In [10]:
df.set_index('name')

      kor  eng  mat
name
홍길동    80   90   85
이기자    70   75   85
최신    100   90   95

### 7-3. set_index 파라미터 - keys, drop

In [11]:
df.set_index('name', drop=True)

      kor  eng  mat
name
홍길동    80   90   85
이기자    70   75   85
최신    100   90   95

In [12]:
df.set_index('name', drop=False)

     name  kor  eng  mat
name
홍길동   홍길동   80   90   85
이기자   이기자   70   75   85
최신     최신  100   90   95

### 7-4. set_index 파라미터 - append, inplace

In [13]:
df.set_index('name', append=True)

        kor  eng  mat
  name
1 홍길동    80   90   85
2 이기자    70   75   85
3 최신    100   90   95

In [14]:
df.set_index('name', inplace=True)
df

      kor  eng  mat
name
홍길동    80   90   85
이기자    70   75   85
최신    100   90   95

## 8. 인덱스 초기화 (reset_index)

### 8-1. 인덱스 완전 삭제 및 초기화 (drop=True)

In [15]:
df.reset_index(drop=True)

   kor  eng  mat
0   80   90   85
1   70   75   85
2  100   90   95

### 8-2. 보존형 인덱스 초기화 (Default, drop=False)

In [16]:
df.reset_index()

  name  kor  eng  mat
0  홍길동   80   90   85
1  이기자   70   75   85
2   최신  100   90   95