In [1]:
import pandas as pd

In [8]:
df = pd.DataFrame(
    {
        'A':[10, 20, 30, 10, 20],
        'B':[20, 30, 40, 50, 60],
        'C':[20, 20, 20, 30, 20]
    }
)
df

    A   B   C
0  10  20  20
1  20  30  20
2  30  40  20
3  10  50  30
4  20  60  20

In [9]:
df.duplicated(['A', 'C'])

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [10]:
df[df.duplicated(['A', 'C'])]

    A   B   C
4  20  60  20

In [14]:
df.drop_duplicates(['A', 'C'], keep='first')

    A   B   C
0  10  20  20
2  30  40  20
3  10  50  30
4  20  60  20

In [15]:
df.drop_duplicates(['A', 'C'], keep='last')

    A   B   C
0  10  20  20
2  30  40  20
3  10  50  30
4  20  60  20